from _typeshed import Incomplete
from django.conf import settings as settings
from django.db import NotSupportedError as NotSupportedError, transaction as transaction
from django.db.backends import utils as utils
from django.db.models.expressions import Col as Col
from django.utils import timezone as timezone
from django.utils.deprecation import RemovedInDjango60Warning as RemovedInDjango60Warning
from django.utils.encoding import force_str as force_str

class BaseDatabaseOperations:
    compiler_module: str
    integer_field_ranges: Incomplete
    set_operators: Incomplete
    cast_data_types: Incomplete
    cast_char_field_without_max_length: Incomplete
    PRECEDING: str
    FOLLOWING: str
    UNBOUNDED_PRECEDING: Incomplete
    UNBOUNDED_FOLLOWING: Incomplete
    CURRENT_ROW: str
    explain_prefix: Incomplete
    connection: Incomplete
    def __init__(self, connection) -> None: ...
    def autoinc_sql(self, table, column) -> None: ...
    def bulk_batch_size(self, fields, objs): ...
    def format_for_duration_arithmetic(self, sql) -> None: ...
    def cache_key_culling_sql(self): ...
    def unification_cast_sql(self, output_field): ...
    def date_extract_sql(self, lookup_type, sql, params) -> None: ...
    def date_trunc_sql(self, lookup_type, sql, params, tzname: Incomplete | None = None) -> None: ...
    def datetime_cast_date_sql(self, sql, params, tzname) -> None: ...
    def datetime_cast_time_sql(self, sql, params, tzname) -> None: ...
    def datetime_extract_sql(self, lookup_type, sql, params, tzname) -> None: ...
    def datetime_trunc_sql(self, lookup_type, sql, params, tzname) -> None: ...
    def time_trunc_sql(self, lookup_type, sql, params, tzname: Incomplete | None = None) -> None: ...
    def time_extract_sql(self, lookup_type, sql, params): ...
    def deferrable_sql(self): ...
    def distinct_sql(self, fields, params): ...
    def fetch_returned_insert_columns(self, cursor, returning_params): ...
    def field_cast_sql(self, db_type, internal_type): ...
    def force_group_by(self): ...
    def force_no_ordering(self): ...
    def for_update_sql(self, nowait: bool = False, skip_locked: bool = False, of=(), no_key: bool = False): ...
    def limit_offset_sql(self, low_mark, high_mark): ...
    def bulk_insert_sql(self, fields, placeholder_rows): ...
    def last_executed_query(self, cursor, sql, params): ...
    def last_insert_id(self, cursor, table_name, pk_name): ...
    def lookup_cast(self, lookup_type, internal_type: Incomplete | None = None): ...
    def max_in_list_size(self) -> None: ...
    def max_name_length(self) -> None: ...
    def no_limit_value(self) -> None: ...
    def pk_default_value(self): ...
    def prepare_sql_script(self, sql): ...
    def process_clob(self, value): ...
    def return_insert_columns(self, fields) -> None: ...
    def compiler(self, compiler_name): ...
    def quote_name(self, name) -> None: ...
    def regex_lookup(self, lookup_type) -> None: ...
    def savepoint_create_sql(self, sid): ...
    def savepoint_commit_sql(self, sid): ...
    def savepoint_rollback_sql(self, sid): ...
    def set_time_zone_sql(self): ...
    def sql_flush(self, style, tables, *, reset_sequences: bool = False, allow_cascade: bool = False) -> None: ...
    def execute_sql_flush(self, sql_list) -> None: ...
    def sequence_reset_by_name_sql(self, style, sequences): ...
    def sequence_reset_sql(self, style, model_list): ...
    def start_transaction_sql(self): ...
    def end_transaction_sql(self, success: bool = True): ...
    def tablespace_sql(self, tablespace, inline: bool = False): ...
    def prep_for_like_query(self, x): ...
    prep_for_iexact_query = prep_for_like_query
    def validate_autopk_value(self, value): ...
    def adapt_unknown_value(self, value): ...
    def adapt_integerfield_value(self, value, internal_type): ...
    def adapt_datefield_value(self, value): ...
    def adapt_datetimefield_value(self, value): ...
    def adapt_timefield_value(self, value): ...
    def adapt_decimalfield_value(self, value, max_digits: Incomplete | None = None, decimal_places: Incomplete | None = None): ...
    def adapt_ipaddressfield_value(self, value): ...
    def adapt_json_value(self, value, encoder): ...
    def year_lookup_bounds_for_date_field(self, value, iso_year: bool = False): ...
    def year_lookup_bounds_for_datetime_field(self, value, iso_year: bool = False): ...
    def get_db_converters(self, expression): ...
    def convert_durationfield_value(self, value, expression, connection): ...
    def check_expression_support(self, expression) -> None: ...
    def conditional_expression_supported_in_where_clause(self, expression): ...
    def combine_expression(self, connector, sub_expressions): ...
    def combine_duration_expression(self, connector, sub_expressions): ...
    def binary_placeholder_sql(self, value): ...
    def modify_insert_params(self, placeholder, params): ...
    def integer_field_range(self, internal_type): ...
    def subtract_temporals(self, internal_type, lhs, rhs): ...
    def window_frame_value(self, value): ...
    def window_frame_rows_start_end(self, start: Incomplete | None = None, end: Incomplete | None = None): ...
    def window_frame_range_start_end(self, start: Incomplete | None = None, end: Incomplete | None = None): ...
    def explain_query_prefix(self, format: Incomplete | None = None, **options): ...
    def insert_statement(self, on_conflict: Incomplete | None = None): ...
    def on_conflict_suffix_sql(self, fields, on_conflict, update_fields, unique_fields): ...
    def prepare_join_on_clause(self, lhs_table, lhs_field, rhs_table, rhs_field): ...
