"""
This type stub file was generated by pyright.
"""

from http import cookies

"""
This type stub file was generated by pyright.
"""
SimpleCookie = cookies.SimpleCookie
def parse_cookie(cookie):
    """
    Return a dictionary parsed from a `Cookie:` header string.
    """
    ...

