"""
This type stub file was generated by pyright.
"""

from django.conf import DEFAULT_STORAGE_ALIAS
from django.utils.functional import LazyObject
from .base import Storage
from .filesystem import FileSystemStorage
from .handler import InvalidStorageError, StorageHandler
from .memory import InMemoryStorage

__all__ = ("FileSystemStorage", "InMemoryStorage", "Storage", "DefaultStorage", "default_storage", "InvalidStorageError", "StorageHandler", "storages")
class DefaultStorage(LazyObject):
    ...


storages = ...
default_storage = ...
