from django.core.exceptions import BadRequest as BadRequest, SuspiciousOperation as SuspiciousOperation

class InvalidSessionKey(SuspiciousOperation): ...
class SuspiciousSession(SuspiciousOperation): ...
class SessionInterrupted(BadRequest): ...
