from django.conf import settings as settings
from django.core.exceptions import PermissionDenied as PermissionDenied
from django.core.mail import mail_managers as mail_managers
from django.http import HttpResponsePermanentRedirect as HttpResponsePermanentRedirect
from django.urls import is_valid_path as is_valid_path
from django.utils.deprecation import MiddlewareMixin as MiddlewareMixin
from django.utils.http import escape_leading_slashes as escape_leading_slashes

class CommonMiddleware(MiddlewareMixin):
    response_redirect_class = HttpResponsePermanentRedirect
    def process_request(self, request): ...
    def should_redirect_with_slash(self, request): ...
    def get_full_path_with_slash(self, request): ...
    def process_response(self, request, response): ...

class BrokenLinkEmailsMiddleware(MiddlewareMixin):
    def process_response(self, request, response): ...
    def is_internal_request(self, domain, referer): ...
    def is_ignorable_request(self, request, uri, domain, referer): ...
