from .signals import user_logged_in as user_logged_in, user_logged_out as user_logged_out, user_login_failed as user_login_failed
from _typeshed import Incomplete
from django.conf import settings as settings
from django.core.exceptions import ImproperlyConfigured as ImproperlyConfigured, PermissionDenied as PermissionDenied
from django.middleware.csrf import rotate_token as rotate_token
from django.utils.crypto import constant_time_compare as constant_time_compare
from django.utils.module_loading import import_string as import_string
from django.views.decorators.debug import sensitive_variables as sensitive_variables

SESSION_KEY: str
BACKEND_SESSION_KEY: str
HASH_SESSION_KEY: str
REDIRECT_FIELD_NAME: str

def load_backend(path): ...
def get_backends(): ...
def authenticate(request: Incomplete | None = None, **credentials): ...
async def aauthenticate(request: Incomplete | None = None, **credentials): ...
def login(request, user, backend: Incomplete | None = None) -> None: ...
async def alogin(request, user, backend: Incomplete | None = None): ...
def logout(request) -> None: ...
async def alogout(request): ...
def get_user_model(): ...
def get_user(request): ...
async def aget_user(request): ...
def get_permission_codename(action, opts): ...
def update_session_auth_hash(request, user) -> None: ...
async def aupdate_session_auth_hash(request, user) -> None: ...
