from _typeshed import Incomplete
from django.conf import settings as settings
from django.contrib.auth import REDIRECT_FIELD_NAME as REDIRECT_FIELD_NAME
from django.contrib.auth.views import redirect_to_login as redirect_to_login
from django.core.exceptions import ImproperlyConfigured as ImproperlyConfigured, PermissionDenied as PermissionDenied
from django.shortcuts import resolve_url as resolve_url

class AccessMixin:
    login_url: Incomplete
    permission_denied_message: str
    raise_exception: bool
    redirect_field_name = REDIRECT_FIELD_NAME
    def get_login_url(self): ...
    def get_permission_denied_message(self): ...
    def get_redirect_field_name(self): ...
    def handle_no_permission(self): ...

class LoginRequiredMixin(AccessMixin):
    def dispatch(self, request, *args, **kwargs): ...

class PermissionRequiredMixin(AccessMixin):
    permission_required: Incomplete
    def get_permission_required(self): ...
    def has_permission(self): ...
    def dispatch(self, request, *args, **kwargs): ...

class UserPassesTestMixin(AccessMixin):
    def test_func(self) -> None: ...
    def get_test_func(self): ...
    def dispatch(self, request, *args, **kwargs): ...
