from _typeshed import Incomplete
from django.db import models as models
from django.db.backends.base.introspection import BaseDatabaseIntrospection as BaseDatabaseIntrospection
from django.db.backends.oracle.oracledb_any import oracledb as oracledb

FieldInfo: Incomplete
TableInfo: Incomplete

class DatabaseIntrospection(BaseDatabaseIntrospection):
    cache_bust_counter: int
    data_types_reverse: Incomplete
    def get_field_type(self, data_type, description): ...
    def get_table_list(self, cursor): ...
    def get_table_description(self, cursor, table_name): ...
    def identifier_converter(self, name): ...
    def get_sequences(self, cursor, table_name, table_fields=()): ...
    def get_relations(self, cursor, table_name): ...
    def get_primary_key_columns(self, cursor, table_name): ...
    def get_constraints(self, cursor, table_name): ...
