from django.db import NotSupportedError as NotSupportedError
from django.db.backends.base.creation import BaseDatabaseCreation as BaseDatabaseCreation

class DatabaseCreation(BaseDatabaseCreation):
    @staticmethod
    def is_in_memory_db(database_name): ...
    def get_test_db_clone_settings(self, suffix): ...
    def test_db_signature(self): ...
    def setup_worker_connection(self, _worker_id) -> None: ...
