"""
This type stub file was generated by pyright.
"""

from django.utils.functional import cached_property

NOT_PROVIDED = ...
class FieldCacheMixin:
    """
    An API for working with the model's fields value cache.

    Subclasses must set self.cache_name to a unique entry for the cache -
    typically the field’s name.
    """
    def get_cache_name(self):
        ...
    
    @cached_property
    def cache_name(self):
        ...
    
    def get_cached_value(self, instance, default=...): # -> object:
        ...
    
    def is_cached(self, instance): # -> bool:
        ...
    
    def set_cached_value(self, instance, value): # -> None:
        ...
    
    def delete_cached_value(self, instance): # -> None:
        ...
    


class CheckFieldDefaultMixin:
    _default_hint = ...
    def check(self, **kwargs):
        ...
    


