from _typeshed import Incomplete

class BaseEmailBackend:
    fail_silently: Incomplete
    def __init__(self, fail_silently: bool = False, **kwargs) -> None: ...
    def open(self) -> None: ...
    def close(self) -> None: ...
    def __enter__(self): ...
    def __exit__(self, exc_type: type[BaseException] | None, exc_value: BaseException | None, traceback: types.TracebackType | None) -> None: ...
    def send_messages(self, email_messages) -> None: ...
