from .exceptions import NoReverseMatch as NoReverseMatch, Resolver404 as Resolver404
from .resolvers import get_ns_resolver as get_ns_resolver, get_resolver as get_resolver
from .utils import get_callable as get_callable
from _typeshed import Incomplete
from django.utils.functional import lazy as lazy
from django.utils.translation import override as override

def resolve(path, urlconf: Incomplete | None = None): ...
def reverse(viewname, urlconf: Incomplete | None = None, args: Incomplete | None = None, kwargs: Incomplete | None = None, current_app: Incomplete | None = None): ...

reverse_lazy: Incomplete

def clear_url_caches() -> None: ...
def set_script_prefix(prefix) -> None: ...
def get_script_prefix(): ...
def clear_script_prefix() -> None: ...
def set_urlconf(urlconf_name) -> None: ...
def get_urlconf(default: Incomplete | None = None): ...
def is_valid_path(path, urlconf: Incomplete | None = None): ...
def translate_url(url, lang_code): ...
