from _typeshed import Incomplete
from django.contrib.gis.gdal import CoordTransform as CoordTransform, SpatialReference as SpatialReference
from django.core.serializers.base import SerializerDoesNotExist as SerializerDoesNotExist
from django.core.serializers.json import Serializer as JSONSerializer

class Serializer(JSONSerializer):
    def start_serialization(self) -> None: ...
    def end_serialization(self) -> None: ...
    geometry_field: Incomplete
    def start_object(self, obj) -> None: ...
    def get_dump_object(self, obj): ...
    def handle_field(self, obj, field) -> None: ...

class Deserializer:
    def __init__(self, *args, **kwargs) -> None: ...
