from _typeshed import Incomplete
from channels.db import database_sync_to_async as database_sync_to_async
from channels.middleware import BaseMiddleware as BaseMiddleware
from channels.sessions import CookieMiddleware as CookieMiddleware, SessionMiddleware as SessionMiddleware
from django.utils.functional import LazyObject

def get_user(scope): ...
def login(scope, user, backend: Incomplete | None = None) -> None: ...
def logout(scope) -> None: ...

class UserLazyObject(LazyObject): ...

class AuthMiddleware(BaseMiddleware):
    def populate_scope(self, scope) -> None: ...
    async def resolve_scope(self, scope) -> None: ...
    async def __call__(self, scope, receive, send): ...

def AuthMiddlewareStack(inner): ...
