from django.contrib.syndication.views import Feed as BaseFeed
from django.utils.feedgenerator import Atom1Feed as Atom1Feed, Rss201rev2Feed as Rss201rev2Feed

class GeoFeedMixin:
    def georss_coords(self, coords): ...
    def add_georss_point(self, handler, coords, w3c_geo: bool = False) -> None: ...
    def add_georss_element(self, handler, item, w3c_geo: bool = False) -> None: ...

class GeoRSSFeed(Rss201rev2Feed, GeoFeedMixin):
    def rss_attributes(self): ...
    def add_item_elements(self, handler, item) -> None: ...
    def add_root_elements(self, handler) -> None: ...

class GeoAtom1Feed(Atom1Feed, GeoFeedMixin):
    def root_attributes(self): ...
    def add_item_elements(self, handler, item) -> None: ...
    def add_root_elements(self, handler) -> None: ...

class W3CGeoFeed(Rss201rev2Feed, GeoFeedMixin):
    def rss_attributes(self): ...
    def add_item_elements(self, handler, item) -> None: ...
    def add_root_elements(self, handler) -> None: ...

class Feed(BaseFeed):
    feed_type = GeoRSSFeed
    def feed_extra_kwargs(self, obj): ...
    def item_extra_kwargs(self, item): ...
