from django.conf import settings as settings
from django.http import HttpResponse as HttpResponse
from django.template import loader as loader

def compress_kml(kml): ...
def render_to_kml(*args, **kwargs): ...
def render_to_kmz(*args, **kwargs): ...
