from .base import InclusionAdminNode as InclusionAdminNode
from _typeshed import Incomplete
from django import template as template
from django.template.context import Context as Context

register: Incomplete

def prepopulated_fields_js(context): ...
def prepopulated_fields_js_tag(parser, token): ...
def submit_row(context): ...
def submit_row_tag(parser, token): ...
def change_form_object_tools_tag(parser, token): ...
def cell_count(inline_admin_form): ...
