from _typeshed import Incomplete
from django.template import Template as Template, TemplateDoesNotExist as TemplateDoesNotExist

class Loader:
    engine: Incomplete
    def __init__(self, engine) -> None: ...
    def get_template(self, template_name, skip: Incomplete | None = None): ...
    def get_template_sources(self, template_name) -> None: ...
    def reset(self) -> None: ...
