from _typeshed import Incomplete
from django.core.exceptions import FullResultSet as FullResultSet
from django.db.models.sql.constants import INNER as INNER, LOUTER as LOUTER
from django.utils.deprecation import RemovedInDjango60Warning as RemovedInDjango60Warning

class MultiJoin(Exception):
    level: Incomplete
    names_with_path: Incomplete
    def __init__(self, names_pos, path_with_names) -> None: ...

class Empty: ...

class Join:
    table_name: Incomplete
    parent_alias: Incomplete
    table_alias: Incomplete
    join_type: Incomplete
    join_fields: Incomplete
    join_cols: Incomplete
    join_field: Incomplete
    nullable: Incomplete
    filtered_relation: Incomplete
    def __init__(self, table_name, parent_alias, table_alias, join_type, join_field, nullable, filtered_relation: Incomplete | None = None) -> None: ...
    def as_sql(self, compiler, connection): ...
    def relabeled_clone(self, change_map): ...
    @property
    def identity(self): ...
    def __eq__(self, other): ...
    def __hash__(self): ...
    def demote(self): ...
    def promote(self): ...

class BaseTable:
    join_type: Incomplete
    parent_alias: Incomplete
    filtered_relation: Incomplete
    table_name: Incomplete
    table_alias: Incomplete
    def __init__(self, table_name, alias) -> None: ...
    def as_sql(self, compiler, connection): ...
    def relabeled_clone(self, change_map): ...
    @property
    def identity(self): ...
    def __eq__(self, other): ...
    def __hash__(self): ...
