from _typeshed import Incomplete
from django.middleware.cache import CacheMiddleware as CacheMiddleware
from django.utils.cache import add_never_cache_headers as add_never_cache_headers, patch_cache_control as patch_cache_control
from django.utils.decorators import decorator_from_middleware_with_args as decorator_from_middleware_with_args

def cache_page(timeout, *, cache: Incomplete | None = None, key_prefix: Incomplete | None = None): ...
def cache_control(**kwargs): ...
def never_cache(view_func): ...
