from django.contrib.auth import get_permission_codename as get_permission_codename
from django.contrib.contenttypes.management import create_contenttypes as create_contenttypes
from django.core import exceptions as exceptions
from django.db import DEFAULT_DB_ALIAS as DEFAULT_DB_ALIAS, router as router

def create_permissions(app_config, verbosity: int = 2, interactive: bool = True, using=..., apps=..., **kwargs) -> None: ...
def get_system_username(): ...
def get_default_username(check_db: bool = True, database=...): ...
