from _typeshed import Incomplete
from django.http import Http404 as Http404, HttpResponse as HttpResponse, HttpResponsePermanentRedirect as HttpResponsePermanentRedirect, HttpResponseRedirect as HttpResponseRedirect
from django.template import loader as loader
from django.urls import NoReverseMatch as NoReverseMatch, reverse as reverse
from django.utils.functional import Promise as Promise

def render(request, template_name, context: Incomplete | None = None, content_type: Incomplete | None = None, status: Incomplete | None = None, using: Incomplete | None = None): ...
def redirect(to, *args, permanent: bool = False, **kwargs): ...
def get_object_or_404(klass, *args, **kwargs): ...
async def aget_object_or_404(klass, *args, **kwargs): ...
def get_list_or_404(klass, *args, **kwargs): ...
async def aget_list_or_404(klass, *args, **kwargs): ...
def resolve_url(to, *args, **kwargs): ...
