from _typeshed import Incomplete
from django.apps import apps as apps
from django.conf import settings as settings
from django.core.serializers.base import SerializerDoesNotExist as SerializerDoesNotExist

BUILTIN_SERIALIZERS: Incomplete

class BadSerializer:
    internal_use_only: bool
    exception: Incomplete
    def __init__(self, exception) -> None: ...
    def __call__(self, *args, **kwargs) -> None: ...

def register_serializer(format, serializer_module, serializers: Incomplete | None = None) -> None: ...
def unregister_serializer(format) -> None: ...
def get_serializer(format): ...
def get_serializer_formats(): ...
def get_public_serializer_formats(): ...
def get_deserializer(format): ...
def serialize(format, queryset, **options): ...
def deserialize(format, stream_or_string, **options): ...
def sort_dependencies(app_list, allow_cycles: bool = False): ...
