from .base import Storage as Storage
from .mixins import StorageSettingsMixin as StorageSettingsMixin
from _typeshed import Incomplete
from django.conf import settings as settings
from django.core.files import File as File, locks as locks
from django.core.files.move import file_move_safe as file_move_safe
from django.core.signals import setting_changed as setting_changed
from django.utils._os import safe_join as safe_join
from django.utils.deconstruct import deconstructible as deconstructible
from django.utils.deprecation import RemovedInDjango60Warning as RemovedInDjango60Warning
from django.utils.encoding import filepath_to_uri as filepath_to_uri
from django.utils.functional import cached_property as cached_property

class FileSystemStorage(Storage, StorageSettingsMixin):
    OS_OPEN_FLAGS: Incomplete
    def __init__(self, location: Incomplete | None = None, base_url: Incomplete | None = None, file_permissions_mode: Incomplete | None = None, directory_permissions_mode: Incomplete | None = None, allow_overwrite: bool = False) -> None: ...
    def base_location(self): ...
    def location(self): ...
    def base_url(self): ...
    def file_permissions_mode(self): ...
    def directory_permissions_mode(self): ...
    def delete(self, name) -> None: ...
    def is_name_available(self, name, max_length: Incomplete | None = None): ...
    def get_alternative_name(self, file_root, file_ext): ...
    def exists(self, name): ...
    def listdir(self, path): ...
    def path(self, name): ...
    def size(self, name): ...
    def url(self, name): ...
    def get_accessed_time(self, name): ...
    def get_created_time(self, name): ...
    def get_modified_time(self, name): ...
