from _typeshed import Incomplete
from django.conf import settings as settings
from django.core.exceptions import ImproperlyConfigured as ImproperlyConfigured
from django.utils.functional import cached_property as cached_property
from django.utils.module_loading import import_string as import_string

class InvalidStorageError(ImproperlyConfigured): ...

class StorageHandler:
    def __init__(self, backends: Incomplete | None = None) -> None: ...
    def backends(self): ...
    def __getitem__(self, alias): ...
    def create_storage(self, params): ...
