"""
This type stub file was generated by pyright.
"""

from typing import Literal
from .utils.version import get_version as get_version

"""
This type stub file was generated by pyright.
"""
VERSION: tuple[int, int, int, Literal["alpha", "beta", "rc", "final"], int]
__version__: str
def setup(set_prefix: bool = ...) -> None:
    ...

