from _typeshed import Incomplete
from django.conf import settings as settings
from django.core.exceptions import ImproperlyConfigured as ImproperlyConfigured
from django.db import models as models
from django.http import Http404 as Http404
from django.utils import timezone as timezone
from django.utils.functional import cached_property as cached_property
from django.views.generic.base import View as View
from django.views.generic.detail import BaseDetailView as BaseDetailView, SingleObjectTemplateResponseMixin as SingleObjectTemplateResponseMixin
from django.views.generic.list import MultipleObjectMixin as MultipleObjectMixin, MultipleObjectTemplateResponseMixin as MultipleObjectTemplateResponseMixin

class YearMixin:
    year_format: str
    year: Incomplete
    def get_year_format(self): ...
    def get_year(self): ...
    def get_next_year(self, date): ...
    def get_previous_year(self, date): ...

class MonthMixin:
    month_format: str
    month: Incomplete
    def get_month_format(self): ...
    def get_month(self): ...
    def get_next_month(self, date): ...
    def get_previous_month(self, date): ...

class DayMixin:
    day_format: str
    day: Incomplete
    def get_day_format(self): ...
    def get_day(self): ...
    def get_next_day(self, date): ...
    def get_previous_day(self, date): ...

class WeekMixin:
    week_format: str
    week: Incomplete
    def get_week_format(self): ...
    def get_week(self): ...
    def get_next_week(self, date): ...
    def get_previous_week(self, date): ...

class DateMixin:
    date_field: Incomplete
    allow_future: bool
    def get_date_field(self): ...
    def get_allow_future(self): ...
    def uses_datetime_field(self): ...

class BaseDateListView(MultipleObjectMixin, DateMixin, View):
    allow_empty: bool
    date_list_period: str
    def get(self, request, *args, **kwargs): ...
    def get_dated_items(self) -> None: ...
    def get_ordering(self): ...
    def get_dated_queryset(self, **lookup): ...
    def get_date_list_period(self): ...
    def get_date_list(self, queryset, date_type: Incomplete | None = None, ordering: str = 'ASC'): ...

class BaseArchiveIndexView(BaseDateListView):
    context_object_name: str
    def get_dated_items(self): ...

class ArchiveIndexView(MultipleObjectTemplateResponseMixin, BaseArchiveIndexView):
    template_name_suffix: str

class BaseYearArchiveView(YearMixin, BaseDateListView):
    date_list_period: str
    make_object_list: bool
    def get_dated_items(self): ...
    def get_make_object_list(self): ...

class YearArchiveView(MultipleObjectTemplateResponseMixin, BaseYearArchiveView):
    template_name_suffix: str

class BaseMonthArchiveView(YearMixin, MonthMixin, BaseDateListView):
    date_list_period: str
    def get_dated_items(self): ...

class MonthArchiveView(MultipleObjectTemplateResponseMixin, BaseMonthArchiveView):
    template_name_suffix: str

class BaseWeekArchiveView(YearMixin, WeekMixin, BaseDateListView):
    def get_dated_items(self): ...

class WeekArchiveView(MultipleObjectTemplateResponseMixin, BaseWeekArchiveView):
    template_name_suffix: str

class BaseDayArchiveView(YearMixin, MonthMixin, DayMixin, BaseDateListView):
    def get_dated_items(self): ...

class DayArchiveView(MultipleObjectTemplateResponseMixin, BaseDayArchiveView):
    template_name_suffix: str

class BaseTodayArchiveView(BaseDayArchiveView):
    def get_dated_items(self): ...

class TodayArchiveView(MultipleObjectTemplateResponseMixin, BaseTodayArchiveView):
    template_name_suffix: str

class BaseDateDetailView(YearMixin, MonthMixin, DayMixin, DateMixin, BaseDetailView):
    def get_object(self, queryset: Incomplete | None = None): ...

class DateDetailView(SingleObjectTemplateResponseMixin, BaseDateDetailView):
    template_name_suffix: str

def timezone_today(): ...
