from _typeshed import Incomplete
from collections.abc import Generator
from django.conf import STATICFILES_STORAGE_ALIAS as STATICFILES_STORAGE_ALIAS, settings as settings
from django.contrib.staticfiles.utils import check_settings as check_settings, matches_patterns as matches_patterns
from django.core.exceptions import ImproperlyConfigured as ImproperlyConfigured
from django.core.files.base import ContentFile as ContentFile
from django.core.files.storage import FileSystemStorage as FileSystemStorage, storages as storages
from django.utils.functional import LazyObject as LazyObject

class StaticFilesStorage(FileSystemStorage):
    base_location: Incomplete
    location: Incomplete
    def __init__(self, location: Incomplete | None = None, base_url: Incomplete | None = None, *args, **kwargs) -> None: ...
    def path(self, name): ...

class HashedFilesMixin:
    default_template: str
    max_post_process_passes: int
    support_js_module_import_aggregation: bool
    patterns: Incomplete
    keep_intermediate_files: bool
    hashed_files: Incomplete
    def __init__(self, *args, **kwargs) -> None: ...
    def file_hash(self, name, content: Incomplete | None = None): ...
    def hashed_name(self, name, content: Incomplete | None = None, filename: Incomplete | None = None): ...
    def url(self, name, force: bool = False): ...
    def url_converter(self, name, hashed_files, template: Incomplete | None = None): ...
    def post_process(self, paths, dry_run: bool = False, **options) -> Generator[Incomplete, Incomplete]: ...
    def clean_name(self, name): ...
    def hash_key(self, name): ...
    def stored_name(self, name): ...

class ManifestFilesMixin(HashedFilesMixin):
    manifest_version: str
    manifest_name: str
    manifest_strict: bool
    keep_intermediate_files: bool
    manifest_storage: Incomplete
    def __init__(self, *args, manifest_storage: Incomplete | None = None, **kwargs) -> None: ...
    def read_manifest(self): ...
    def load_manifest(self): ...
    hashed_files: Incomplete
    def post_process(self, *args, **kwargs) -> Generator[Incomplete, Incomplete]: ...
    manifest_hash: Incomplete
    def save_manifest(self) -> None: ...
    def stored_name(self, name): ...

class ManifestStaticFilesStorage(ManifestFilesMixin, StaticFilesStorage): ...
class ConfiguredStorage(LazyObject): ...

staticfiles_storage: Incomplete
