from _typeshed import Incomplete
from collections.abc import Generator
from django.conf import settings as settings
from django.core.exceptions import ImproperlyConfigured as ImproperlyConfigured

def matches_patterns(path, patterns): ...
def get_files(storage, ignore_patterns: Incomplete | None = None, location: str = '') -> Generator[Incomplete, Incomplete]: ...
def check_settings(base_url: Incomplete | None = None) -> None: ...
