from _typeshed import Incomplete
from django.db.backends.base.introspection import BaseDatabaseIntrospection as BaseDatabaseIntrospection
from django.db.models import Index as Index

FieldInfo: Incomplete
TableInfo: Incomplete

class DatabaseIntrospection(BaseDatabaseIntrospection):
    data_types_reverse: Incomplete
    index_default_access_method: str
    ignored_tables: Incomplete
    def get_field_type(self, data_type, description): ...
    def get_table_list(self, cursor): ...
    def get_table_description(self, cursor, table_name): ...
    def get_sequences(self, cursor, table_name, table_fields=()): ...
    def get_relations(self, cursor, table_name): ...
    def get_constraints(self, cursor, table_name): ...
