from _typeshed import Incomplete
from django.conf import settings as settings
from django.contrib.sessions.backends.db import SessionStore as DBStore
from django.core.cache import caches as caches

KEY_PREFIX: str
logger: Incomplete

class SessionStore(DBStore):
    cache_key_prefix = KEY_PREFIX
    def __init__(self, session_key: Incomplete | None = None) -> None: ...
    @property
    def cache_key(self): ...
    async def acache_key(self): ...
    def load(self): ...
    async def aload(self): ...
    def exists(self, session_key): ...
    async def aexists(self, session_key): ...
    def save(self, must_create: bool = False) -> None: ...
    async def asave(self, must_create: bool = False) -> None: ...
    def delete(self, session_key: Incomplete | None = None) -> None: ...
    async def adelete(self, session_key: Incomplete | None = None) -> None: ...
    def flush(self) -> None: ...
    async def aflush(self) -> None: ...
