from _typeshed import Incomplete
from django.conf import settings as settings
from django.contrib.sessions.backends.base import CreateError as CreateError, SessionBase as SessionBase, UpdateError as UpdateError
from django.core.cache import caches as caches

KEY_PREFIX: str

class SessionStore(SessionBase):
    cache_key_prefix = KEY_PREFIX
    def __init__(self, session_key: Incomplete | None = None) -> None: ...
    @property
    def cache_key(self): ...
    async def acache_key(self): ...
    def load(self): ...
    async def aload(self): ...
    modified: bool
    def create(self) -> None: ...
    async def acreate(self) -> None: ...
    def save(self, must_create: bool = False): ...
    async def asave(self, must_create: bool = False): ...
    def exists(self, session_key): ...
    async def aexists(self, session_key): ...
    def delete(self, session_key: Incomplete | None = None) -> None: ...
    async def adelete(self, session_key: Incomplete | None = None) -> None: ...
    @classmethod
    def clear_expired(cls) -> None: ...
    @classmethod
    async def aclear_expired(cls) -> None: ...
