from _typeshed import Incomplete
from django.conf import settings as settings
from django.contrib.sessions.backends.base import CreateError as CreateError, SessionBase as SessionBase, UpdateError as UpdateError, VALID_KEY_CHARS as VALID_KEY_CHARS
from django.contrib.sessions.exceptions import InvalidSessionKey as InvalidSessionKey
from django.core.exceptions import ImproperlyConfigured as ImproperlyConfigured, SuspiciousOperation as SuspiciousOperation

class SessionStore(SessionBase):
    storage_path: Incomplete
    file_prefix: Incomplete
    def __init__(self, session_key: Incomplete | None = None) -> None: ...
    def load(self): ...
    async def aload(self): ...
    modified: bool
    def create(self) -> None: ...
    async def acreate(self): ...
    def save(self, must_create: bool = False): ...
    async def asave(self, must_create: bool = False): ...
    def exists(self, session_key): ...
    async def aexists(self, session_key): ...
    def delete(self, session_key: Incomplete | None = None) -> None: ...
    async def adelete(self, session_key: Incomplete | None = None): ...
    @classmethod
    def clear_expired(cls) -> None: ...
    @classmethod
    async def aclear_expired(cls) -> None: ...
