from _typeshed import Incomplete
from django.contrib.sessions.backends.base import SessionBase as SessionBase
from django.core import signing as signing

class SessionStore(SessionBase):
    def load(self): ...
    async def aload(self): ...
    modified: bool
    def create(self) -> None: ...
    async def acreate(self): ...
    def save(self, must_create: bool = False) -> None: ...
    async def asave(self, must_create: bool = False): ...
    def exists(self, session_key: Incomplete | None = None): ...
    async def aexists(self, session_key: Incomplete | None = None): ...
    def delete(self, session_key: Incomplete | None = None) -> None: ...
    async def adelete(self, session_key: Incomplete | None = None): ...
    def cycle_key(self) -> None: ...
    async def acycle_key(self): ...
    @classmethod
    def clear_expired(cls) -> None: ...
    @classmethod
    async def aclear_expired(cls) -> None: ...
