"""
This type stub file was generated by pyright.
"""

from django.dispatch import receiver
from django.utils.autoreload import autoreload_started, file_changed

"""
This type stub file was generated by pyright.
"""
def get_template_directories():
    ...

def reset_loaders():
    ...

@receiver(autoreload_started, dispatch_uid="template_loaders_watch_changes")
def watch_for_template_changes(sender, **kwargs):
    ...

@receiver(file_changed, dispatch_uid="template_loaders_file_changed")
def template_changed(sender, file_path, **kwargs):
    ...

