"""
This type stub file was generated by pyright.
"""

import functools
from django.utils.functional import cached_property

"""
This type stub file was generated by pyright.
"""
class Engine:
    default_builtins = ...
    def __init__(self, dirs=..., app_dirs=..., context_processors=..., debug=..., loaders=..., string_if_invalid=..., file_charset=..., libraries=..., builtins=..., autoescape=...) -> None:
        ...
    
    def __repr__(self):
        ...
    
    @staticmethod
    @functools.lru_cache
    def get_default():
        """
        Return the first DjangoTemplates backend that's configured, or raise
        ImproperlyConfigured if none are configured.

        This is required for preserving historical APIs that rely on a
        globally available, implicitly configured engine such as:

        >>> from django.template import Context, Template
        >>> template = Template("Hello {{ name }}!")
        >>> context = Context({'name': "world"})
        >>> template.render(context)
        'Hello world!'
        """
        ...
    
    @cached_property
    def template_context_processors(self):
        ...
    
    def get_template_builtins(self, builtins):
        ...
    
    def get_template_libraries(self, libraries):
        ...
    
    @cached_property
    def template_loaders(self):
        ...
    
    def get_template_loaders(self, template_loaders):
        ...
    
    def find_template_loader(self, loader):
        ...
    
    def find_template(self, name, dirs=..., skip=...):
        ...
    
    def from_string(self, template_code):
        """
        Return a compiled Template object for the given template code,
        handling template inheritance recursively.
        """
        ...
    
    def get_template(self, template_name):
        """
        Return a compiled Template object for the given template name,
        handling template inheritance recursively.
        """
        ...
    
    def render_to_string(self, template_name, context=...):
        """
        Render the template specified by template_name with the given context.
        For use in Django's test suite.
        """
        ...
    
    def select_template(self, template_name_list):
        """
        Given a list of template names, return the first that can be loaded.
        """
        ...
    


