from django.db.models.fields import DecimalField as DecimalField, FloatField as FloatField, IntegerField as IntegerField
from django.db.models.functions import Cast as Cast

class FixDecimalInputMixin:
    def as_postgresql(self, compiler, connection, **extra_context): ...

class FixDurationInputMixin:
    def as_mysql(self, compiler, connection, **extra_context): ...
    def as_oracle(self, compiler, connection, **extra_context): ...

class NumericOutputFieldMixin: ...
