"""
This type stub file was generated by pyright.
"""

import functools

"""
This type stub file was generated by pyright.
"""
class IntConverter:
    regex = ...
    def to_python(self, value):
        ...
    
    def to_url(self, value):
        ...
    


class StringConverter:
    regex = ...
    def to_python(self, value):
        ...
    
    def to_url(self, value):
        ...
    


class UUIDConverter:
    regex = ...
    def to_python(self, value):
        ...
    
    def to_url(self, value):
        ...
    


class SlugConverter(StringConverter):
    regex = ...


class PathConverter(StringConverter):
    regex = ...


DEFAULT_CONVERTERS = ...
REGISTERED_CONVERTERS = ...
def register_converter(converter, type_name):
    ...

@functools.cache
def get_converters():
    ...

