from _typeshed import Incomplete
from django.db import DatabaseError as DatabaseError
from django.db.backends.sqlite3.schema import DatabaseSchemaEditor as DatabaseSchemaEditor

class SpatialiteSchemaEditor(DatabaseSchemaEditor):
    sql_add_geometry_column: str
    sql_add_spatial_index: str
    sql_drop_spatial_index: str
    sql_recover_geometry_metadata: str
    sql_remove_geometry_metadata: str
    sql_discard_geometry_columns: str
    sql_update_geometry_columns: str
    geometry_tables: Incomplete
    geometry_sql: Incomplete
    def __init__(self, *args, **kwargs) -> None: ...
    def geo_quote_name(self, name): ...
    def column_sql(self, model, field, include_default: bool = False): ...
    def remove_geometry_metadata(self, model, field) -> None: ...
    def create_model(self, model) -> None: ...
    def delete_model(self, model, **kwargs) -> None: ...
    def add_field(self, model, field) -> None: ...
    def remove_field(self, model, field) -> None: ...
    def alter_db_table(self, model, old_db_table, new_db_table) -> None: ...
