"""
This type stub file was generated by pyright.
"""

from django.utils.functional import cached_property

"""
This type stub file was generated by pyright.
"""
class ConnectionProxy:
    """Proxy for accessing a connection object's attributes."""
    def __init__(self, connections, alias) -> None:
        ...
    
    def __getattr__(self, item):
        ...
    
    def __setattr__(self, name, value):
        ...
    
    def __delattr__(self, name):
        ...
    
    def __contains__(self, key):
        ...
    
    def __eq__(self, other) -> bool:
        ...
    


class ConnectionDoesNotExist(Exception):
    ...


class BaseConnectionHandler:
    settings_name = ...
    exception_class = ConnectionDoesNotExist
    thread_critical = ...
    def __init__(self, settings=...) -> None:
        ...
    
    @cached_property
    def settings(self):
        ...
    
    def configure_settings(self, settings):
        ...
    
    def create_connection(self, alias):
        ...
    
    def __getitem__(self, alias):
        ...
    
    def __setitem__(self, key, value):
        ...
    
    def __delitem__(self, key):
        ...
    
    def __iter__(self):
        ...
    
    def all(self, initialized_only=...):
        ...
    
    def close_all(self):
        ...
    


