from _typeshed import Incomplete
from collections.abc import Generator

def make_model_tuple(model): ...
def resolve_callables(mapping) -> Generator[Incomplete]: ...
def unpickle_named_row(names, values): ...
def create_namedtuple_class(*names): ...

class AltersData:
    def __init_subclass__(cls, **kwargs) -> None: ...
