from . import Error as Error, Tags as Tags, Warning as Warning, register as register
from django.conf import settings as settings
from django.core.exceptions import ViewDoesNotExist as ViewDoesNotExist

def check_url_config(app_configs, **kwargs): ...
def check_resolver(resolver): ...
def check_url_namespaces_unique(app_configs, **kwargs): ...
def get_warning_for_invalid_pattern(pattern): ...
def check_url_settings(app_configs, **kwargs): ...
def E006(name): ...
def check_custom_error_handlers(app_configs, **kwargs): ...
