from .. import Error as Error, Tags as Tags, Warning as Warning, register as register
from _typeshed import Incomplete
from django.conf import settings as settings
from django.core.exceptions import ImproperlyConfigured as ImproperlyConfigured

CROSS_ORIGIN_OPENER_POLICY_VALUES: Incomplete
REFERRER_POLICY_VALUES: Incomplete
SECRET_KEY_INSECURE_PREFIX: str
SECRET_KEY_MIN_LENGTH: int
SECRET_KEY_MIN_UNIQUE_CHARACTERS: int
SECRET_KEY_WARNING_MSG: Incomplete
W001: Incomplete
W002: Incomplete
W004: Incomplete
W005: Incomplete
W006: Incomplete
W008: Incomplete
W009: Incomplete
W018: Incomplete
W019: Incomplete
W020: Incomplete
W021: Incomplete
W022: Incomplete
E023: Incomplete
E024: Incomplete
W025: Incomplete

def check_security_middleware(app_configs, **kwargs): ...
def check_xframe_options_middleware(app_configs, **kwargs): ...
def check_sts(app_configs, **kwargs): ...
def check_sts_include_subdomains(app_configs, **kwargs): ...
def check_sts_preload(app_configs, **kwargs): ...
def check_content_type_nosniff(app_configs, **kwargs): ...
def check_ssl_redirect(app_configs, **kwargs): ...
def check_secret_key(app_configs, **kwargs): ...
def check_secret_key_fallbacks(app_configs, **kwargs): ...
def check_debug(app_configs, **kwargs): ...
def check_xframe_deny(app_configs, **kwargs): ...
def check_allowed_hosts(app_configs, **kwargs): ...
def check_referrer_policy(app_configs, **kwargs): ...
def check_cross_origin_opener_policy(app_configs, **kwargs): ...
