from .exceptions import AmbiguityError as AmbiguityError, BadMigrationError as BadMigrationError, InconsistentMigrationHistory as InconsistentMigrationHistory, NodeNotFoundError as NodeNotFoundError
from _typeshed import Incomplete
from django.apps import apps as apps
from django.conf import settings as settings
from django.db.migrations.graph import MigrationGraph as MigrationGraph
from django.db.migrations.recorder import MigrationRecorder as MigrationRecorder

MIGRATIONS_MODULE_NAME: str

class MigrationLoader:
    connection: Incomplete
    disk_migrations: Incomplete
    applied_migrations: Incomplete
    ignore_no_migrations: Incomplete
    replace_migrations: Incomplete
    def __init__(self, connection, load: bool = True, ignore_no_migrations: bool = False, replace_migrations: bool = True) -> None: ...
    @classmethod
    def migrations_module(cls, app_label): ...
    unmigrated_apps: Incomplete
    migrated_apps: Incomplete
    def load_disk(self) -> None: ...
    def get_migration(self, app_label, name_prefix): ...
    def get_migration_by_prefix(self, app_label, name_prefix): ...
    def check_key(self, key, current_app): ...
    def add_internal_dependencies(self, key, migration) -> None: ...
    def add_external_dependencies(self, key, migration) -> None: ...
    graph: Incomplete
    replacements: Incomplete
    def build_graph(self) -> None: ...
    def check_consistent_history(self, connection) -> None: ...
    def detect_conflicts(self): ...
    def project_state(self, nodes: Incomplete | None = None, at_end: bool = True): ...
    def collect_sql(self, plan): ...
