from .loader import MigrationLoader as MigrationLoader
from _typeshed import Incomplete
from django.apps import apps as apps
from django.core.management.base import OutputWrapper as OutputWrapper
from django.db.models import NOT_PROVIDED as NOT_PROVIDED
from django.utils import timezone as timezone
from django.utils.version import get_docs_version as get_docs_version

class MigrationQuestioner:
    defaults: Incomplete
    specified_apps: Incomplete
    dry_run: Incomplete
    def __init__(self, defaults: Incomplete | None = None, specified_apps: Incomplete | None = None, dry_run: Incomplete | None = None) -> None: ...
    def ask_initial(self, app_label): ...
    def ask_not_null_addition(self, field_name, model_name) -> None: ...
    def ask_not_null_alteration(self, field_name, model_name) -> None: ...
    def ask_rename(self, model_name, old_name, new_name, field_instance): ...
    def ask_rename_model(self, old_model_state, new_model_state): ...
    def ask_merge(self, app_label): ...
    def ask_auto_now_add_addition(self, field_name, model_name) -> None: ...
    def ask_unique_callable_default_addition(self, field_name, model_name) -> None: ...

class InteractiveMigrationQuestioner(MigrationQuestioner):
    prompt_output: Incomplete
    def __init__(self, defaults: Incomplete | None = None, specified_apps: Incomplete | None = None, dry_run: Incomplete | None = None, prompt_output: Incomplete | None = None) -> None: ...
    def ask_not_null_addition(self, field_name, model_name): ...
    def ask_not_null_alteration(self, field_name, model_name): ...
    def ask_rename(self, model_name, old_name, new_name, field_instance): ...
    def ask_rename_model(self, old_model_state, new_model_state): ...
    def ask_merge(self, app_label): ...
    def ask_auto_now_add_addition(self, field_name, model_name): ...
    def ask_unique_callable_default_addition(self, field_name, model_name) -> None: ...

class NonInteractiveMigrationQuestioner(MigrationQuestioner):
    verbosity: Incomplete
    log: Incomplete
    def __init__(self, defaults: Incomplete | None = None, specified_apps: Incomplete | None = None, dry_run: Incomplete | None = None, verbosity: int = 1, log: Incomplete | None = None) -> None: ...
    def log_lack_of_migration(self, field_name, model_name, reason) -> None: ...
    def ask_not_null_addition(self, field_name, model_name) -> None: ...
    def ask_not_null_alteration(self, field_name, model_name): ...
    def ask_auto_now_add_addition(self, field_name, model_name) -> None: ...
