from .exceptions import MigrationSchemaMissing as MigrationSchemaMissing
from _typeshed import Incomplete
from django.apps.registry import Apps as Apps
from django.db import DatabaseError as DatabaseError, models as models
from django.utils.functional import classproperty as classproperty
from django.utils.timezone import now as now

class MigrationRecorder:
    def Migration(cls): ...
    connection: Incomplete
    def __init__(self, connection) -> None: ...
    @property
    def migration_qs(self): ...
    def has_table(self): ...
    def ensure_schema(self) -> None: ...
    def applied_migrations(self): ...
    def record_applied(self, app, name) -> None: ...
    def record_unapplied(self, app, name) -> None: ...
    def flush(self) -> None: ...
