from _typeshed import Incomplete
from django import get_version as get_version
from django.apps import apps as apps
from django.conf import SettingsReference as SettingsReference
from django.db import migrations as migrations
from django.db.migrations.loader import MigrationLoader as MigrationLoader
from django.db.migrations.serializer import Serializer as Serializer, serializer_factory as serializer_factory
from django.utils.inspect import get_func_args as get_func_args
from django.utils.module_loading import module_dir as module_dir
from django.utils.timezone import now as now

class OperationWriter:
    operation: Incomplete
    buff: Incomplete
    indentation: Incomplete
    def __init__(self, operation, indentation: int = 2) -> None: ...
    def serialize(self): ...
    def indent(self) -> None: ...
    def unindent(self) -> None: ...
    def feed(self, line) -> None: ...
    def render(self): ...

class MigrationWriter:
    migration: Incomplete
    include_header: Incomplete
    needs_manual_porting: bool
    def __init__(self, migration, include_header: bool = True) -> None: ...
    def as_string(self): ...
    @property
    def basedir(self): ...
    @property
    def filename(self): ...
    @property
    def path(self): ...
    @classmethod
    def serialize(cls, value): ...
    @classmethod
    def register_serializer(cls, type_, serializer) -> None: ...
    @classmethod
    def unregister_serializer(cls, type_) -> None: ...

MIGRATION_HEADER_TEMPLATE: str
MIGRATION_TEMPLATE: str
