"""
This type stub file was generated by pyright.
"""

from collections.abc import Callable, Sequence
from typing import Any, overload
from django.http.response import HttpResponse, HttpResponseBase
from django.urls import URLPattern, URLResolver, include as include
from typing_extensions import TypeAlias

"""
This type stub file was generated by pyright.
"""
handler400: str | Callable[..., HttpResponse]
handler403: str | Callable[..., HttpResponse]
handler404: str | Callable[..., HttpResponse]
handler500: str | Callable[..., HttpResponse]
_IncludedURLConf: TypeAlias = tuple[Sequence[URLResolver | URLPattern], str | None, str | None]
@overload
def url(regex: str, view: Callable[..., HttpResponseBase], kwargs: dict[str, Any] | None = ..., name: str | None = ...) -> URLPattern:
    ...

@overload
def url(regex: str, view: _IncludedURLConf, kwargs: dict[str, Any] | None = ..., name: str | None = ...) -> URLResolver:
    ...

@overload
def url(regex: str, view: Sequence[URLResolver | str], kwargs: dict[str, Any] | None = ..., name: str | None = ...) -> URLResolver:
    ...

