from _typeshed import Incomplete
from django.contrib.gis.db.models import GeometryField as GeometryField
from django.db.backends.oracle.schema import DatabaseSchemaEditor as DatabaseSchemaEditor
from django.db.backends.utils import strip_quotes as strip_quotes, truncate_name as truncate_name

class OracleGISSchemaEditor(DatabaseSchemaEditor):
    sql_add_geometry_metadata: str
    sql_add_spatial_index: str
    sql_clear_geometry_table_metadata: str
    sql_clear_geometry_field_metadata: str
    geometry_sql: Incomplete
    def __init__(self, *args, **kwargs) -> None: ...
    def geo_quote_name(self, name): ...
    def quote_value(self, value): ...
    def column_sql(self, model, field, include_default: bool = False): ...
    def create_model(self, model) -> None: ...
    def delete_model(self, model) -> None: ...
    def add_field(self, model, field) -> None: ...
    def remove_field(self, model, field) -> None: ...
    def run_geometry_sql(self) -> None: ...
