from _typeshed import Incomplete
from django.db.backends.base.features import BaseDatabaseFeatures as BaseDatabaseFeatures
from django.utils.functional import cached_property as cached_property

class DatabaseFeatures(BaseDatabaseFeatures):
    empty_fetchmany_value: Incomplete
    related_fields_match_type: bool
    allow_sliced_subqueries_with_in: bool
    has_select_for_update: bool
    has_select_for_update_nowait: bool
    supports_forward_references: bool
    supports_regex_backreferencing: bool
    supports_date_lookup_using_string: bool
    supports_timezones: bool
    requires_explicit_null_ordering_when_grouping: bool
    atomic_transactions: bool
    can_clone_databases: bool
    supports_comments: bool
    supports_comments_inline: bool
    supports_temporal_subtraction: bool
    supports_slicing_ordering_in_compound: bool
    supports_index_on_text_field: bool
    supports_over_clause: bool
    supports_frame_range_fixed_distance: bool
    supports_update_conflicts: bool
    delete_can_self_reference_subquery: bool
    create_test_procedure_without_params_sql: str
    create_test_procedure_with_int_param_sql: str
    create_test_table_with_composite_primary_key: str
    supports_partial_indexes: bool
    collate_as_index_expression: bool
    insert_test_table_with_defaults: str
    supports_order_by_nulls_modifier: bool
    order_by_nulls_first: bool
    supports_logical_xor: bool
    supports_stored_generated_columns: bool
    supports_virtual_generated_columns: bool
    def minimum_database_version(self): ...
    def test_collations(self): ...
    test_now_utc_template: str
    def django_test_skips(self): ...
    def allows_auto_pk_0(self): ...
    def update_can_self_select(self): ...
    def can_introspect_foreign_keys(self): ...
    def introspected_field_types(self): ...
    def can_return_columns_from_insert(self): ...
    can_return_rows_from_bulk_insert: Incomplete
    def has_zoneinfo_database(self): ...
    def is_sql_auto_is_null_enabled(self): ...
    def supports_column_check_constraints(self): ...
    supports_table_check_constraints: Incomplete
    def can_introspect_check_constraints(self): ...
    def has_select_for_update_skip_locked(self): ...
    def has_select_for_update_of(self): ...
    def supports_explain_analyze(self): ...
    def supported_explain_formats(self): ...
    def supports_transactions(self): ...
    def ignores_table_name_case(self): ...
    def supports_default_in_lead_lag(self): ...
    def can_introspect_json_field(self): ...
    def supports_index_column_ordering(self): ...
    def supports_expression_indexes(self): ...
    def supports_select_intersection(self): ...
    supports_select_difference: Incomplete
    def can_rename_index(self): ...
    def supports_expression_defaults(self): ...
    def has_native_uuid_field(self): ...
    def allows_group_by_selected_pks(self): ...
