from django.utils import termcolors as termcolors

HAS_COLORAMA: bool

def supports_color(): ...

class Style: ...

def make_style(config_string: str = ''): ...
def no_style(): ...
def color_style(force_color: bool = False): ...
