from django.apps import apps as apps
from django.db import models as models

def sql_flush(style, connection, reset_sequences: bool = True, allow_cascade: bool = False): ...
def emit_pre_migrate_signal(verbosity, interactive, db, **kwargs) -> None: ...
def emit_post_migrate_signal(verbosity, interactive, db, **kwargs) -> None: ...
