from .base import CommandError as CommandError, CommandParser as CommandParser
from _typeshed import Incomplete
from django.utils.crypto import get_random_string as get_random_string
from django.utils.encoding import DEFAULT_LOCALE_ENCODING as DEFAULT_LOCALE_ENCODING

def popen_wrapper(args, stdout_encoding: str = 'utf-8'): ...
def handle_extensions(extensions): ...
def find_command(cmd, path: Incomplete | None = None, pathext: Incomplete | None = None): ...
def get_random_secret_key(): ...
def parse_apps_and_model_labels(labels): ...
def get_command_line_option(argv, option): ...
def normalize_path_patterns(patterns): ...
def is_ignored_path(path, ignore_patterns): ...
def find_formatters(): ...
def run_formatters(written_files, black_path=...) -> None: ...
