from ..db import aclose_old_connections as aclose_old_connections
from ..exceptions import StopConsumer as StopConsumer
from _typeshed import Incomplete
from channels.consumer import AsyncConsumer as AsyncConsumer

class AsyncHttpConsumer(AsyncConsumer):
    body: Incomplete
    def __init__(self, *args, **kwargs) -> None: ...
    async def send_headers(self, *, status: int = 200, headers: Incomplete | None = None) -> None: ...
    async def send_body(self, body, *, more_body: bool = False) -> None: ...
    async def send_response(self, status, body, **kwargs) -> None: ...
    async def handle(self, body) -> None: ...
    async def disconnect(self) -> None: ...
    async def http_request(self, message) -> None: ...
    async def http_disconnect(self, message) -> None: ...
