from _typeshed import Incomplete

def action(function: Incomplete | None = None, *, permissions: Incomplete | None = None, description: Incomplete | None = None): ...
def display(function: Incomplete | None = None, *, boolean: Incomplete | None = None, ordering: Incomplete | None = None, description: Incomplete | None = None, empty_value: Incomplete | None = None): ...
def register(*models, site: Incomplete | None = None): ...
