from django.dispatch import receiver as receiver
from django.template import engines as engines
from django.template.backends.django import DjangoTemplates as DjangoTemplates
from django.utils._os import to_path as to_path
from django.utils.autoreload import autoreload_started as autoreload_started, file_changed as file_changed, is_django_path as is_django_path

def get_template_directories(): ...
def reset_loaders() -> None: ...
def watch_for_template_changes(sender, **kwargs) -> None: ...
def template_changed(sender, file_path, **kwargs): ...
