from django.conf import settings as settings
from django.middleware.csrf import get_token as get_token
from django.utils.functional import SimpleLazyObject as SimpleLazyObject, lazy as lazy

def csrf(request): ...
def debug(request): ...
def i18n(request): ...
def tz(request): ...
def static(request): ...
def media(request): ...
def request(request): ...
