from .base import VARIABLE_ATTRIBUTE_SEPARATOR as VARIABLE_ATTRIBUTE_SEPARATOR
from .library import Library as Library
from _typeshed import Incomplete
from django.utils import formats as formats
from django.utils.dateformat import format as format, time_format as time_format
from django.utils.encoding import iri_to_uri as iri_to_uri
from django.utils.html import avoid_wrapping as avoid_wrapping, conditional_escape as conditional_escape, escape as escape, escapejs as escapejs, linebreaks as linebreaks, strip_tags as strip_tags
from django.utils.safestring import SafeData as SafeData, mark_safe as mark_safe
from django.utils.text import Truncator as Truncator, normalize_newlines as normalize_newlines, phone2numeric as phone2numeric, wrap as wrap
from django.utils.timesince import timesince as timesince, timeuntil as timeuntil
from django.utils.translation import gettext as gettext, ngettext as ngettext

register: Incomplete

def stringfilter(func): ...
def addslashes(value): ...
def capfirst(value): ...
def escapejs_filter(value): ...
def json_script(value, element_id: Incomplete | None = None): ...
def floatformat(text, arg: int = -1): ...
def iriencode(value): ...
def linenumbers(value, autoescape: bool = True): ...
def lower(value): ...
def make_list(value): ...
def slugify(value): ...
def stringformat(value, arg): ...
def title(value): ...
def truncatechars(value, arg): ...
def truncatechars_html(value, arg): ...
def truncatewords(value, arg): ...
def truncatewords_html(value, arg): ...
def upper(value): ...
def urlencode(value, safe: Incomplete | None = None): ...
def urlize(value, autoescape: bool = True): ...
def urlizetrunc(value, limit, autoescape: bool = True): ...
def wordcount(value): ...
def wordwrap(value, arg): ...
def ljust(value, arg): ...
def rjust(value, arg): ...
def center(value, arg): ...
def cut(value, arg): ...
def escape_filter(value): ...
def escapeseq(value): ...
def force_escape(value): ...
def linebreaks_filter(value, autoescape: bool = True): ...
def linebreaksbr(value, autoescape: bool = True): ...
def safe(value): ...
def safeseq(value): ...
def striptags(value): ...
def dictsort(value, arg): ...
def dictsortreversed(value, arg): ...
def first(value): ...
def join(value, arg, autoescape: bool = True): ...
def last(value): ...
def length(value): ...
def random(value): ...
def slice_filter(value, arg): ...
def unordered_list(value, autoescape: bool = True): ...
def add(value, arg): ...
def get_digit(value, arg): ...
def date(value, arg: Incomplete | None = None): ...
def time(value, arg: Incomplete | None = None): ...
def timesince_filter(value, arg: Incomplete | None = None): ...
def timeuntil_filter(value, arg: Incomplete | None = None): ...
def default(value, arg): ...
def default_if_none(value, arg): ...
def divisibleby(value, arg): ...
def yesno(value, arg: Incomplete | None = None): ...
def filesizeformat(bytes_): ...
def pluralize(value, arg: str = 's'): ...
def phone2numeric_filter(value): ...
def pprint(value): ...
