from . import engines as engines
from .exceptions import TemplateDoesNotExist as TemplateDoesNotExist
from _typeshed import Incomplete

def get_template(template_name, using: Incomplete | None = None): ...
def select_template(template_name_list, using: Incomplete | None = None): ...
def render_to_string(template_name, context: Incomplete | None = None, request: Incomplete | None = None, using: Incomplete | None = None): ...
