from _typeshed import Incomplete
from django.apps import apps as apps
from django.conf import settings as settings
from django.core.exceptions import ImproperlyConfigured as ImproperlyConfigured
from django.utils.functional import cached_property as cached_property
from django.utils.module_loading import import_string as import_string

class InvalidTemplateEngineError(ImproperlyConfigured): ...

class EngineHandler:
    def __init__(self, templates: Incomplete | None = None) -> None: ...
    def templates(self): ...
    def __getitem__(self, alias): ...
    def __iter__(self): ...
    def all(self): ...

def get_app_template_dirs(dirname): ...
