from _typeshed import Incomplete
from django.contrib.gis.db import models as models
from django.contrib.gis.db.backends.base.adapter import WKTAdapter as WKTAdapter
from django.contrib.gis.db.backends.base.operations import BaseSpatialOperations as BaseSpatialOperations
from django.contrib.gis.db.backends.utils import SpatialOperator as SpatialOperator
from django.contrib.gis.geos.geometry import GEOSGeometryBase as GEOSGeometryBase
from django.contrib.gis.geos.prototypes.io import wkb_r as wkb_r
from django.contrib.gis.measure import Distance as Distance
from django.db.backends.mysql.operations import DatabaseOperations as DatabaseOperations
from django.utils.functional import cached_property as cached_property

class MySQLOperations(BaseSpatialOperations, DatabaseOperations):
    name: str
    geom_func_prefix: str
    Adapter = WKTAdapter
    def mariadb(self): ...
    def mysql(self): ...
    def select(self): ...
    def from_text(self): ...
    def collect(self): ...
    def gis_operators(self): ...
    def disallowed_aggregates(self): ...
    function_names: Incomplete
    def unsupported_functions(self): ...
    def geo_db_type(self, f): ...
    def get_distance(self, f, value, lookup_type): ...
    def get_geometry_converter(self, expression): ...
    def spatial_aggregate_name(self, agg_name): ...
