from _typeshed import Incomplete
from django.contrib.gis.db.models import GeometryField as GeometryField
from django.db import OperationalError as OperationalError
from django.db.backends.mysql.schema import DatabaseSchemaEditor as DatabaseSchemaEditor

logger: Incomplete

class MySQLGISSchemaEditor(DatabaseSchemaEditor):
    sql_add_spatial_index: str
    geometry_sql: Incomplete
    def __init__(self, *args, **kwargs) -> None: ...
    def skip_default(self, field): ...
    def quote_value(self, value): ...
    def column_sql(self, model, field, include_default: bool = False): ...
    def create_model(self, model) -> None: ...
    def add_field(self, model, field) -> None: ...
    def remove_field(self, model, field) -> None: ...
    def create_spatial_indexes(self) -> None: ...
