from _typeshed import Incomplete
from django.apps import apps as apps
from django.contrib.admin.exceptions import NotRegistered as NotRegistered
from django.core.exceptions import FieldDoesNotExist as FieldDoesNotExist, PermissionDenied as PermissionDenied
from django.http import Http404 as Http404, JsonResponse as JsonResponse
from django.views.generic.list import BaseListView as BaseListView

class AutocompleteJsonView(BaseListView):
    paginate_by: int
    admin_site: Incomplete
    object_list: Incomplete
    def get(self, request, *args, **kwargs): ...
    def serialize_result(self, obj, to_field_name): ...
    def get_paginator(self, *args, **kwargs): ...
    def get_queryset(self): ...
    def process_request(self, request): ...
    def has_perm(self, request, obj: Incomplete | None = None): ...
