from _typeshed import Incomplete
from datetime import datetime
from django.template import Library as Library, Node as Node, TemplateSyntaxError as TemplateSyntaxError
from django.utils import timezone as timezone

register: Incomplete

class datetimeobject(datetime): ...

def localtime(value): ...
def utc(value): ...
def do_timezone(value, arg): ...

class LocalTimeNode(Node):
    nodelist: Incomplete
    use_tz: Incomplete
    def __init__(self, nodelist, use_tz) -> None: ...
    def render(self, context): ...

class TimezoneNode(Node):
    nodelist: Incomplete
    tz: Incomplete
    def __init__(self, nodelist, tz) -> None: ...
    def render(self, context): ...

class GetCurrentTimezoneNode(Node):
    variable: Incomplete
    def __init__(self, variable) -> None: ...
    def render(self, context): ...

def localtime_tag(parser, token): ...
def timezone_tag(parser, token): ...
def get_current_timezone_tag(parser, token): ...
