from _typeshed import Incomplete
from django.conf import settings as settings
from django.core.cache import caches as caches
from django.http import HttpResponse as HttpResponse, HttpResponseNotModified as HttpResponseNotModified
from django.utils.http import http_date as http_date, parse_etags as parse_etags, parse_http_date_safe as parse_http_date_safe, quote_etag as quote_etag
from django.utils.log import log_response as log_response
from django.utils.timezone import get_current_timezone_name as get_current_timezone_name
from django.utils.translation import get_language as get_language

cc_delim_re: Incomplete

def patch_cache_control(response, **kwargs): ...
def get_max_age(response): ...
def set_response_etag(response): ...
def get_conditional_response(request, etag: Incomplete | None = None, last_modified: Incomplete | None = None, response: Incomplete | None = None): ...
def patch_response_headers(response, cache_timeout: Incomplete | None = None) -> None: ...
def add_never_cache_headers(response) -> None: ...
def patch_vary_headers(response, newheaders) -> None: ...
def has_vary_header(response, header_query): ...
def get_cache_key(request, key_prefix: Incomplete | None = None, method: str = 'GET', cache: Incomplete | None = None): ...
def learn_cache_key(request, response, cache_timeout: Incomplete | None = None, key_prefix: Incomplete | None = None, cache: Incomplete | None = None): ...
