from _typeshed import Incomplete
from django.conf import settings as settings
from django.utils.encoding import force_bytes as force_bytes

class InvalidAlgorithm(ValueError): ...

def salted_hmac(key_salt, value, secret: Incomplete | None = None, *, algorithm: str = 'sha1'): ...

RANDOM_STRING_CHARS: str

def get_random_string(length, allowed_chars=...): ...
def constant_time_compare(val1, val2): ...
def pbkdf2(password, salt, iterations, dklen: int = 0, digest: Incomplete | None = None): ...
