from _typeshed import Incomplete

class classonlymethod(classmethod):
    def __get__(self, instance, cls: Incomplete | None = None): ...

def method_decorator(decorator, name: str = ''): ...
def decorator_from_middleware_with_args(middleware_class): ...
def decorator_from_middleware(middleware_class): ...
def make_middleware_decorator(middleware_class): ...
def sync_and_async_middleware(func): ...
def sync_only_middleware(func): ...
def async_only_middleware(func): ...
