from _typeshed import Incomplete
from django.utils.functional import Promise as Promise

class DjangoUnicodeDecodeError(UnicodeDecodeError): ...

def smart_str(s, encoding: str = 'utf-8', strings_only: bool = False, errors: str = 'strict'): ...
def is_protected_type(obj): ...
def force_str(s, encoding: str = 'utf-8', strings_only: bool = False, errors: str = 'strict'): ...
def smart_bytes(s, encoding: str = 'utf-8', strings_only: bool = False, errors: str = 'strict'): ...
def force_bytes(s, encoding: str = 'utf-8', strings_only: bool = False, errors: str = 'strict'): ...
def iri_to_uri(iri): ...
def uri_to_iri(uri): ...
def escape_uri_path(path): ...
def punycode(domain): ...
def repercent_broken_unicode(path): ...
def filepath_to_uri(path): ...
def get_system_encoding(): ...

DEFAULT_LOCALE_ENCODING: Incomplete
