from _typeshed import Incomplete
from collections.abc import Generator
from django.conf import settings as settings
from django.utils import dateformat as dateformat, numberformat as numberformat
from django.utils.functional import lazy as lazy
from django.utils.translation import check_for_language as check_for_language, get_language as get_language, to_locale as to_locale

ISO_INPUT_FORMATS: Incomplete
FORMAT_SETTINGS: Incomplete

def reset_format_cache() -> None: ...
def iter_format_modules(lang, format_module_path: Incomplete | None = None) -> Generator[Incomplete]: ...
def get_format_modules(lang: Incomplete | None = None): ...
def get_format(format_type, lang: Incomplete | None = None, use_l10n: Incomplete | None = None): ...

get_format_lazy: Incomplete

def date_format(value, format: Incomplete | None = None, use_l10n: Incomplete | None = None): ...
def time_format(value, format: Incomplete | None = None, use_l10n: Incomplete | None = None): ...
def number_format(value, decimal_pos: Incomplete | None = None, use_l10n: Incomplete | None = None, force_grouping: bool = False): ...
def localize(value, use_l10n: Incomplete | None = None): ...
def localize_input(value, default: Incomplete | None = None): ...
def sanitize_strftime_format(fmt): ...
def sanitize_separators(value): ...
