from _typeshed import Incomplete
from django.utils.datastructures import MultiValueDict as MultiValueDict

ETAG_MATCH: Incomplete
MONTHS: Incomplete
RFC1123_DATE: Incomplete
RFC850_DATE: Incomplete
ASCTIME_DATE: Incomplete
RFC3986_GENDELIMS: str
RFC3986_SUBDELIMS: str

def urlencode(query, doseq: bool = False): ...
def http_date(epoch_seconds: Incomplete | None = None): ...
def parse_http_date(date): ...
def parse_http_date_safe(date): ...
def base36_to_int(s): ...
def int_to_base36(i): ...
def urlsafe_base64_encode(s): ...
def urlsafe_base64_decode(s): ...
def parse_etags(etag_str): ...
def quote_etag(etag_str): ...
def is_same_domain(host, pattern): ...
def url_has_allowed_host_and_scheme(url, allowed_hosts, require_https: bool = False): ...
def escape_leading_slashes(url): ...
def parse_header_parameters(line): ...
def content_disposition_header(as_attachment, filename): ...
