from _typeshed import Incomplete

ARG_KINDS: Incomplete

def get_func_args(func): ...
def get_func_full_args(func): ...
def func_accepts_kwargs(func): ...
def func_accepts_var_args(func): ...
def method_has_no_args(meth): ...
def func_supports_parameter(func, name): ...
