from _typeshed import Incomplete

COMMON_P: str
WORDS: Incomplete
COMMON_WORDS: Incomplete

def sentence(): ...
def paragraph(): ...
def paragraphs(count, common: bool = True): ...
def words(count, common: bool = True): ...
