def cached_import(module_path, class_name): ...
def import_string(dotted_path): ...
def autodiscover_modules(*args, **kwargs) -> None: ...
def module_has_submodule(package, module_name): ...
def module_dir(module): ...
