from _typeshed import Incomplete
from collections.abc import Generator
from django.utils.functional import SimpleLazyObject as SimpleLazyObject

ESCAPE_MAPPINGS: Incomplete

class Choice(list): ...
class Group(list): ...
class NonCapture(list): ...

def normalize(pattern): ...
def next_char(input_iter) -> Generator[Incomplete]: ...
def walk_to_end(ch, input_iter) -> None: ...
def get_quantifier(ch, input_iter): ...
def contains(source, inst): ...
def flatten_result(source): ...
