from ..generic.websocket import AsyncWebsocketConsumer as AsyncWebsocketConsumer
from _typeshed import Incomplete

class OriginValidator:
    application: Incomplete
    allowed_origins: Incomplete
    def __init__(self, application, allowed_origins) -> None: ...
    async def __call__(self, scope, receive, send): ...
    def valid_origin(self, parsed_origin): ...
    def validate_origin(self, parsed_origin): ...
    def match_allowed_origin(self, parsed_origin, pattern): ...
    def get_origin_port(self, origin): ...

def AllowedHostsOriginValidator(application): ...

class WebsocketDenier(AsyncWebsocketConsumer):
    async def connect(self) -> None: ...
