from _typeshed import Incomplete
from django.core.management.base import BaseCommand as BaseCommand

def module_to_dict(module, omittable=...): ...

class Command(BaseCommand):
    help: str
    requires_system_checks: Incomplete
    def add_arguments(self, parser) -> None: ...
    def handle(self, **options): ...
    def output_hash(self, user_settings, default_settings, **options): ...
    def output_unified(self, user_settings, default_settings, **options): ...
