from _typeshed import Incomplete
from django.core.management import BaseCommand as BaseCommand, CommandError as CommandError
from django.utils.datastructures import OrderedSet as OrderedSet

class Command(BaseCommand):
    help: str
    requires_system_checks: Incomplete
    shells: Incomplete
    def add_arguments(self, parser) -> None: ...
    def ipython(self, options) -> None: ...
    def bpython(self, options) -> None: ...
    def python(self, options) -> None: ...
    def handle(self, **options): ...
