from _typeshed import Incomplete
from django.apps import apps as apps
from django.core.checks import Error as Error

def check_generic_foreign_keys(app_configs: Incomplete | None = None, **kwargs): ...
def check_model_name_lengths(app_configs: Incomplete | None = None, **kwargs): ...
