from django.db import connections as connections
from django.db.backends.base.base import NO_DB_ALIAS as NO_DB_ALIAS
from django.db.backends.postgresql.psycopg_any import is_psycopg3 as is_psycopg3

def get_type_oids(connection_alias, type_name): ...
def get_hstore_oids(connection_alias): ...
def get_citext_oids(connection_alias): ...
def register_type_handlers(connection, **kwargs) -> None: ...
